linters:
  disable-all: true
  enable:
    - gofumpt
    - govet
    - gci
    - staticcheck

run:
  skip-dirs:
    - tls
    - tls_compact

linters-settings:
  gci:
    custom-order: true
    sections:
      - standard
      - prefix(github.com/sagernet/)
      - default
  staticcheck:
    go: '1.20'
